---
# install and start
- block:
  - name: install packages
    package: name=MariaDB-server state=present

  - name: start service
    service: name=mysql state=started enabled=yes

  - name: expose ports
    firewalld:
      port: "{{ port }}"
      state: enabled
      permanent: yes
      immediate: yes
      offline: yes
    loop: "{{ db_srv_ports }}"
    loop_control:
      loop_var: port
  become: yes
  when: ansible_facts.services['firewalld.service'] is defined

- name: configure root password
  mysql_user:
    login_user: root
    login_password: "{{ db_srv_root_pass }}"
    name: root
    password: "{{ db_srv_root_pass }}"
    check_implicit_admin: true
    priv: "*.*:ALL,GRANT"
    login_unix_socket: "{{ db_srv_socket }}"
  become: yes

- name: configure hosted root account
  mysql_user:
    login_user: root
    login_password: "{{ db_srv_root_pass }}"
    name: root
    password: "{{ db_srv_root_pass }}"
    host: "{{ db_srv_root_host }}"
    priv: "*.*:ALL,GRANT"
    login_unix_socket: "{{ db_srv_socket }}"

- name: remove anonymous accounts
  mysql_user:
    login_user: root
    login_password: "{{ db_srv_root_pass }}"
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: "{{ db_srv_socket }}"

- name: create users
  mysql_user:
    login_user: root
    login_password: "{{ db_srv_root_pass }}"
    name: "{{ conf.name }}"
    password: "{{ conf.pass | default(db_srv_default_user_pass, true) }}"
    host: "{{ conf.host | default(db_srv_default_user_host, true) }}"
    priv: "{{ conf.dbname | default(db_srv_default_user_dbname, true) }}.*:ALL"
    append_privs: yes
    state: present
    login_unix_socket: "{{ db_srv_socket }}"
  loop: "{{ db_srv_users }}"
  loop_control:
    loop_var: conf
    label: "{{ conf.name }}:{{ conf.host }}"
